### ISSUE TITLE
 Validate Input

### ISSUE THREAD

**Issue by AlessandroJuleo** [AlessandroJuleo/Sherlock-Numerical#10]
Add input validation to ensure the guess is a number.
Provide appropriate feedback if the input is not a valid number or is outside the range (e.g., an alert message like "Please enter a number between 1 and 100").

**Comment by Azugr** [comment]
Input validation has been successfully implemented to ensure the player's guess is a valid number. If the input is not a number or falls outside the range of 1 to 100, the game provides appropriate feedback to the player with an alert message such as 'Please enter a number between 1 and 100.'
Implementation Details:

    Input is validated to ensure that only numbers are accepted.
    If the input is not a valid number or is outside the range of 1 to 100, the player receives an alert or error message.
    The game does not count invalid inputs as attempts, ensuring the counter remains accurate.

Testing confirmed that invalid inputs (such as letters, symbols, and numbers outside the range) are properly handled, and the appropriate feedback is displayed. No issues were found during testing.
