### ISSUE TITLE
Implement Light/Dark Mode Toggle

### ISSUE THREAD

**Issue by AlessandroJuleo** [AlessandroJuleo/Sherlock-Numerical#11]
Add a toggle to switch between light and dark themes.
Ensure that all elements of the game, such as buttons and input fields, are styled appropriately for each mode.

**Comment by Azugr** [comment]
The Light/Dark Mode Toggle functionality has not been implemented yet. To provide users with the ability to switch between light and dark themes, we need to outline the steps required to implement this feature.
Steps to Implement:

    Create a toggle button: Add a switch or button to the user interface that allows users to toggle between light and dark modes.
    Define CSS themes:
        Create a light theme and a dark theme using appropriate CSS variables or classes.
        Use CSS to adjust background colors, text colors, and other UI elements for both modes.
    JavaScript to toggle the mode: Implement JavaScript functionality that:
        Switches between the light and dark theme when the button is clicked.
        Stores the user's theme preference (light or dark) in localStorage so it persists across sessions.
    Test the toggle: Ensure that the toggle works across different devices and browsers. Make sure the themes are applied correctly and persist after a page reload.

Next Steps:

    Begin implementing the light and dark themes in CSS.
    Create the JavaScript functionality to toggle between the themes and store user preferences.
    Perform testing to ensure the mode switch works smoothly and the user’s preference is saved.
