### ISSUE TITLE
 Add Animation to Play Button

### ISSUE THREAD

**Issue by AlessandroJuleo** [AlessandroJuleo/Sherlock-Numerical#12]
Add an animation effect (e.g., darkening or shadow) when the player hovers over the "Play Now" button.
Ensure that the animation works in both light and dark modes.

**Comment by Azugr** [comment]
"The hover animation effect has been successfully implemented for the 'Play Now' button. The button now darkens and applies a shadow effect when the player hovers over it. This animation works seamlessly in both light and dark modes.
Implementation Details:

    A subtle darkening effect and shadow have been added to the 'Play Now' button on hover.
    The animation effect adapts to both light and dark modes, ensuring a consistent and visually appealing user experience in either theme.
    CSS transitions were used to create a smooth animation effect on hover.

Testing confirmed that the animation works across various devices and browsers, and it functions correctly in both light and dark modes. No issues were found during testing.
