### ISSUE TITLE
Code Cleanup and Optimization

### ISSUE THREAD

**Issue by AlessandroJuleo** [AlessandroJuleo/Sherlock-Numerical#13]
Refactor the code to remove redundancy and ensure best practices.
Comment the code for better readability and maintainability.

**Comment by Azugr** [comment]
The code has been successfully refactored to remove redundancy and follow best practices. Additionally, comments have been added to improve readability and maintainability.
Refactoring Details:

    Removed redundant code: Common logic, such as input validation, has been abstracted into reusable functions.
    Best practices: The code now follows modern best practices:
        Used const and let for variable declarations.
        Consolidated event listeners to prevent repetition.
        Functions are now smaller and focused on specific responsibilities.
    Improved readability and maintainability:
        Meaningful variable and function names have been used.
        Clear and concise comments have been added to explain the purpose of functions and logic.

Testing confirmed that the refactored code works as expected, with no functional regressions or issues identified. The codebase is now more maintainable and easier to understand.
