### ISSUE TITLE
Test Game Functionality

### ISSUE THREAD

**Issue by AlessandroJuleo** [AlessandroJuleo/Sherlock-Numerical#14]
Test each part of the game (input, random number generation, feedback, attempts counter) to ensure there are no bugs.
Create a checklist for testing edge cases (e.g., entering letters instead of numbers, trying a number outside the allowed range, etc.).

**Comment by Azugr** [comment]
Input validation has been tested thoroughly, and all edge cases have been handled. Below is the checklist of scenarios we tested to ensure robust input handling:
Input Validation Checklist:

Entering non-numeric characters (letters, symbols).
Entering a number outside the allowed range.
Entering blank input.
Entering valid number with extra spaces.
Entering decimal numbers.

    Entering multiple numbers in one input.

No bugs or unexpected behaviors were found. Input validation works as expected.
