### ISSUE TITLE
Improve Accessibility

### ISSUE THREAD

**Issue by AlessandroJuleo** [AlessandroJuleo/Sherlock-Numerical#15]
Add labels for input fields to improve accessibility.
Ensure the game can be played using keyboard navigation only.

**Comment by Azugr** [comment]
"Accessibility improvements have been successfully implemented by adding labels for input fields and ensuring that the game can be played using keyboard navigation only. This enhances the user experience, especially for players relying on screen readers or those using the keyboard to navigate.
Implementation Details:

    Labels Added: Accessible <label> elements have been associated with the input fields, improving support for screen readers and enhancing usability.
        Example: The guess input field is now linked with a label using the for attribute and corresponding id on the input.
        This ensures users understand the purpose of each field and can navigate them easily.
    Keyboard Navigation: The game can be fully navigated using only the keyboard.
        The 'Play Now' and 'Submit' buttons, as well as the 'Play Again' button, are focusable using Tab, and they can be activated using the Enter key.
        The input field is focusable with Tab, and the game functionality is operable without using the mouse.

Testing confirmed that all interactive elements are reachable and functional via keyboard navigation. The game works seamlessly with screen readers, and no issues were found during testing.
