### ISSUE TITLE
Make Game Responsive

### ISSUE THREAD

**Issue by AlessandroJuleo** [AlessandroJuleo/Sherlock-Numerical#16]
Adjust the game layout so that it works well on different screen sizes (e.g., desktop, tablet, mobile).
Test the layout on different devices to ensure a smooth user experience.

**Comment by Azugr** [comment]
The game layout has been successfully adjusted for responsiveness using Tailwind CSS. The layout now adapts smoothly across different screen sizes (desktop, tablet, and mobile) to provide a seamless user experience.
Implementation Details:

    Tailwind Responsive Classes: Tailwind's built-in responsive utility classes (e.g., sm:, md:, lg:, and xl:) were used to handle layout adjustments for different screen sizes. This ensures elements are sized and positioned correctly across devices.
    Flexible Grid and Flexbox Layouts: Tailwind's grid and flex utilities were applied to create a fluid and flexible layout that rearranges content depending on screen size.
    Responsive Typography and Spacing: Tailwind's responsive typography and spacing utilities (text-sm, text-lg, p-4, etc.) were used to optimize readability and spacing across various devices.

Testing was performed on multiple devices (mobile, tablet, desktop), and the layout adjusts perfectly based on the screen size, with no layout issues found. Both portrait and landscape orientations were tested. The layout remains smooth and user-friendly in all cases.
