### ISSUE TITLE
Generate Random Number

### ISSUE THREAD

**Issue by AlessandroJuleo** [AlessandroJuleo/Sherlock-Numerical#3]
We need to implement functionality to generate a random number between 1 and 100.
Ensure the random number is generated each time the game starts or restarts.

**Comment by Azugr** [comment]
The functionality to generate a random number between 1 and 100 has been successfully implemented. A new random number is generated every time the game starts or restarts. The logic ensures that a fresh number is used for each session, providing a consistent and fair gameplay experience.
Implementation Details:

    The random number generation uses a secure method to ensure randomness (Math.random() in JavaScript, for example).
    The number is within the range of 1 to 100, inclusive.
    Each restart triggers the random number generation, ensuring that no number repeats unless by chance.

Testing confirms that the random number is properly regenerated each time the game restarts. No issues were found during testing
