### ISSUE TITLE
Capture User Guess 

### ISSUE THREAD

**Issue by AlessandroJuleo** [AlessandroJuleo/Sherlock-Numerical#4]
We need to set up input functionality for the player to enter their guess.
Validate that the guess is between 1 and 100 and store it.

**Comment by Azugr** [comment]
The input functionality for the player to enter their guess has been successfully implemented. The input is validated to ensure that the guess is a number between 1 and 100. If the input is invalid (e.g., not a number or outside the valid range), the game prompts the player to enter a valid guess.
Implementation Details:

    Input field accepts numeric values.
    The input is validated to ensure the guess is between 1 and 100.
    Invalid inputs, such as non-numeric values or numbers outside the range, are handled gracefully with error messages.
    The valid guess is stored for further processing in the game (e.g., comparing it to the random number).

Testing confirmed that invalid inputs are rejected appropriately, and valid inputs are stored and processed correctly. No issues were found during validation and storage testing
