### ISSUE TITLE
 Compare User Guess to Random Number

### ISSUE THREAD

**Issue by AlessandroJuleo** [AlessandroJuleo/Sherlock-Numerical#5]
We need to implement the logic to compare the player's guess to the randomly generated number.
Provide feedback for each guess, such as "Too high," "Too low," or "Correct!".

**Comment by Azugr** [comment]
The logic to compare the player's guess to the randomly generated number has been successfully implemented. The game now provides feedback based on the player's guess, indicating whether the guess is 'Too high,' 'Too low,' or 'Correct!'.
Implementation Details:

    Each guess is compared to the random number generated at the start of the game.
    Feedback is provided to the player:
        'Too high' if the guess is greater than the random number.
        'Too low' if the guess is less than the random number.
        'Correct!' if the guess matches the random number, signaling the end of the game.
    The feedback guides the player to continue guessing until the correct number is found.

Testing confirmed that all feedback responses are correct based on the player's input, and the game behaves as expected in various scenarios. No issues were found during the comparison and feedback testing
