### ISSUE TITLE
Track Number of Attempts

### ISSUE THREAD

**Issue by AlessandroJuleo** [AlessandroJuleo/Sherlock-Numerical#6]
Add a counter to keep track of how many guesses the player has made.
Display the number of attempts to the player after each guess.

**Comment by Azugr** [comment]
The guess counter has been successfully implemented. The game now tracks how many guesses the player has made and displays the number of attempts after each guess.
Implementation Details:

    A counter has been added that increments after each valid guess.
    The number of attempts is displayed to the player after each guess, giving real-time feedback on how many guesses have been made.
    The counter resets each time the game restarts, ensuring accurate tracking for each new game session.

Testing confirmed that the counter increments correctly with each guess and that the number of attempts is displayed accurately. No issues were found during testing
