### ISSUE TITLE
Create Basic User Interface

### ISSUE THREAD

**Issue by AlessandroJuleo** [AlessandroJuleo/Sherlock-Numerical#7]
Create input fields for the player to enter their guess.
Add a button to submit the guess.
Add a paragraph to display feedback messages like "Too high," "Too low," or "Correct!".

**Comment by Azugr** [comment]
The input fields, submit button, and feedback display have been successfully implemented. The player can now enter their guess, submit it via a button, and receive real-time feedback in a designated paragraph.
Implementation Details:

    An input field has been created for the player to enter their guess.
    A submit button is provided to allow the player to submit their guess.
    A paragraph element has been added to display feedback messages based on the player's guess:
        'Too high' if the guess exceeds the target number.
        'Too low' if the guess is below the target number.
        'Correct!' if the guess matches the target number, indicating the end of the game.

Testing confirmed that the input, button, and feedback display work as expected, with all feedback messages being displayed appropriately. No issues were found during testing
