### ISSUE TITLE
Display Number of Attempts

### ISSUE THREAD

**Issue by AlessandroJuleo** [AlessandroJuleo/Sherlock-Numerical#8]
Display the current number of attempts in a prominent location on the page.
Ensure the number updates each time the player makes a guess.

**Comment by Azugr** [comment]
"The current number of attempts is now displayed prominently on the page. The number of attempts updates each time the player makes a guess, providing clear and real-time feedback to the player.
Implementation Details:

    The number of attempts is displayed in a prominent location on the page to ensure it's easily visible to the player.
    The attempt counter updates dynamically each time a valid guess is made.
    The display resets when the game restarts, ensuring accuracy in each session.

Testing confirmed that the number of attempts is displayed correctly and updates immediately after each guess. No issues were found during testing.
