### ISSUE TITLE
Implement Game Restart Functionality

### ISSUE THREAD

**Issue by AlessandroJuleo** [AlessandroJuleo/Sherlock-Numerical#9]
Add a "Play Again" button that appears when the player guesses correctly.
Ensure the random number and the number of attempts are reset.

**Comment by Azugr** [comment]
A 'Play Again' button has been successfully implemented. The button appears when the player guesses correctly, allowing them to start a new game. When the game is reset, a new random number is generated, and the number of attempts is reset to zero.
Implementation Details:

    A 'Play Again' button appears only when the player guesses the correct number.
    Upon clicking the 'Play Again' button, the game resets:
        A new random number is generated.
        The attempt counter resets to zero.
        The input field and feedback are cleared, ready for a new game.

Testing confirmed that the 'Play Again' button appears after a correct guess and that both the random number and attempt counter reset properly when starting a new game. No issues were found during testing.
